[tool.ruff]
line-length = 88
target-version = "py312"
exclude = [
    ".git",
    ".ruff_cache",
    ".venv",
    "__pycache__",
    "venv",
    "build",
    "dist",
]

[tool.ruff.lint]
select = [
    "E",     # pycodestyle errors
    "W",     # pycodestyle warnings
    "F",     # pyflakes
    "I",     # isort
    "B",     # flake8-bugbear
    "C4",    # flake8-comprehensions
    "UP",    # pyupgrade
    "N",     # pep8-naming
    "SIM",   # flake8-simplify
    "RUF",   # Ruff-specific rules
]
ignore = [
    "E501",  # line too long (handled by formatter)
    "B007",  # Loop control variable not used within body
    "B008",  # do not perform function calls in argument defaults
    "B904",  # raise without from inside except
    "N806",  # Variable in function should be lowercase (_LOGGER is convention)
    "SIM105", # contextlib.suppress
    "SIM117", # Use single with for multiple contexts
    "TID252", # Relative imports from parent modules
    "UP038",  # Use X | Y for type unions (requires Python 3.10+)
    "RUF013", # PEP 484 prohibits implicit Optional
]

[tool.ruff.lint.per-file-ignores]
"tests/*" = ["S101"]  # Allow assert in tests

[tool.ruff.lint.isort]
known-first-party = ["custom_components.sunlit"]
combine-as-imports = true
force-sort-within-sections = true

[tool.black]
line-length = 88
target-version = ["py312"]
exclude = '''
/(
    \.git
  | \.hg
  | \.mypy_cache
  | \.tox
  | \.venv
  | _build
  | buck-out
  | build
  | dist
)/
'''

[tool.isort]
profile = "black"
line_length = 88
force_sort_within_sections = true
combine_as_imports = true
known_first_party = ["custom_components.sunlit"]
